import = ["/home/hacker/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true
working_directory = "None"

[cursor.style]
shape = "Block"

[font]
size = 15.0

[font.bold]
family = "FiraCode"
style = "Bold"

[font.bold_italic]
family = "FiraCode"
style = "Bold Italic"

[font.italic]
family = "FiraCode"
style = "Italic"

[font.normal]
family = "FiraCode"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
action = "ClearSelection"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchBackward"
key = "S"
mods = "Shift|Alt"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"


[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 1.0
